# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 912f5028baeb97e6ad7fd8455bbeb2e975de4344f0f81af4f3e0a7e46700867722c93946b5490f31056af2dc67908d05914e10e8c4cdcc11d634ef223e0e83c6

test:
  secret_key_base: b3f5787ff704604792d89a93165e24ba7c15d3ba1f083269f734b104ce715d627258e1d4ddbca5282ad41c29152fdd02a6faacb03e12a8c420760573ca068e10

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
